#lang yosys
; SMT-LIBv2 description generated by Yosys 0.23+25 (git sha1 13e4f343b, clang 10.0.0-4ubuntu1 -fPIC -Os)
; yosys-smt2-stdt
; yosys-smt2-module adder
(declare-datatype |adder_s| ((|adder_mk|
  (|adder_is| Bool)
  (|adder#0| (_ BitVec 32)) ; \a
  (|adder#1| (_ BitVec 32)) ; \b
)))
; yosys-smt2-input a 32
; yosys-smt2-witness {"offset": 0, "path": ["\\a"], "smtname": "a", "smtoffset": 0, "type": "input", "width": 32}
(define-fun |adder_n a| ((state |adder_s|)) (_ BitVec 32) (|adder#0| state))
; yosys-smt2-input b 32
; yosys-smt2-witness {"offset": 0, "path": ["\\b"], "smtname": "b", "smtoffset": 0, "type": "input", "width": 32}
(define-fun |adder_n b| ((state |adder_s|)) (_ BitVec 32) (|adder#1| state))
(define-fun |adder#2| ((state |adder_s|)) (_ BitVec 32) (bvadd (|adder#0| state) (|adder#1| state))) ; \c
; yosys-smt2-output c 32
(define-fun |adder_n c| ((state |adder_s|)) (_ BitVec 32) (|adder#2| state))
(define-fun |adder_a| ((state |adder_s|)) Bool true)
(define-fun |adder_u| ((state |adder_s|)) Bool true)
(define-fun |adder_i| ((state |adder_s|)) Bool true)
(define-fun |adder_h| ((state |adder_s|)) Bool true)
(define-fun |adder_t| ((state |adder_s|) (next_state |adder_s|)) Bool true) ; end of module adder
; yosys-smt2-topmod adder
; end of yosys output

